version: '3'
services:
  fuzzm:
    image: fuzzm:latest
    build:
      context: ../fuzzm
#     args:
#     - proxy_host=<proxy_host>
#     - proxy_port=<proxy_port>
    links:
    - rabbit
    volumes:
    - ".:/root/tftp"
    working_dir: "/root/tftp"
    entrypoint:
    - wait-for-it.sh
    - rabbit:5672
    - --
    - ./fuzz-tftp.sh
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672:15672"
    expose:
    - "5672"
  tftprelay:
    image: tftprelay:latest
    build: 
      context: .
#     args:
#     - proxy=<proxy_host>:<proxy_port>
    privileged: true
    links:
    - rabbit
    - tftp
    volumes:
    - ".:/root/tftp"
    - "../base-receiver:/root/base-receiver"
    entrypoint:
    - wait-for-it.sh
    - rabbit:5672
    - --
    - python3
    - relay.py
    - -t
    - tftp
    - -f
    - rabbit
  tftp:
    image: pghalliday/tftp
    expose:
    - "69/udp"
