version: '3'
services:
  fuzzm:
    image: fuzzm:latest
    build:
      context: ../../fuzzm
      args:
      - proxy_host=${PROXY_HOST}
      - proxy_port=${PROXY_PORT}
    links:
    - rabbit
    volumes:
    - ".:/root/tftp"
    working_dir: "/root/tftp"
    entrypoint:
    - /bin/sh
    - -c
    - "umask 000 && wait-for-it.sh -t 60 rabbit:5672 -- ./fuzz-tftp.sh"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672"
    expose:
    - "5672"
  tftprelay:
    image: tftprelay:latest
    build: 
      context: .
      args:
      - proxy=${HTTP_PROXY}
    privileged: true
    links:
    - rabbit
    - tftp
    volumes:
    - "../../relay-base:/root/relay-base"
    entrypoint:
    - /bin/sh
    - -c
    - "wait-for-it.sh -t 60 rabbit:5672 -- python3 relay.py --target tftp --amqp rabbit"
  tftp:
    image: pghalliday/tftp
    expose:
    - "69/udp"
