version: '3'
services:
  fuzzm:
    build:
       args:
       - proxy_host=${PROXY_HOST}
       - proxy_port=${PROXY_PORT}
       context: .
    image: fuzzm:latest
    entrypoint:
    - /bin/sh
    - -c
    - "umask 000 && mkdir -p /root/fuzzm/bin && cp /usr/local/bin/fuzzm.jar /root/fuzzm/bin/."
    volumes:
    - ./fuzzm:/root/fuzzm
