version: '3'
services:
  fuzzm:
    image: fuzzm:latest
    build:
      context: ../../fuzzm
      args:
      - proxy_host=${PROXY_HOST}
      - proxy_port=${PROXY_PORT}
    links:
    - rabbit
    volumes:
    - ".:/root/fsm"
    working_dir: "/root/fsm"
    entrypoint:
    - /bin/sh
    - -c
    - "wait-for-it.sh rabbit:5672 -- ./fuzz-fsm.sh"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672:15672"
    expose:
    - "5672"
  fsmrelay:
    image: fsmrelay:latest
    build: 
      context: .
      args:
      - proxy=${HTTP_PROXY}
    privileged: true
    links:
    - rabbit
    - fsm
    volumes:
    - ".:/root/fsm"
    - "../../relay-base:/root/relay-base"
    working_dir: "/root/fsm"
    entrypoint:
    - /bin/sh
    - -c
    - "wait-for-it.sh rabbit:5672 -- ./relay-fsm.sh"
  fsm:
    image: fsm:latest
    build:
      context: fsm_demo
      args:
      - proxy=${HTTP_PROXY}
    privileged: true
    working_dir: "/root/fsm"
    entrypoint:
    - ./fsm.sh
    expose:
    - "1515/udp"
