version: '3'
services:
  fuzzm:
    image: fuzzm:latest
    build:
     context: ../fuzzm      
     args:
     - proxy_host=${PROXY_HOST}
     - proxy_port=${PROXY_PORT}
    ports:
    - "1718"
    links:
    - rabbit
    volumes:
    - .:/root/model
    entrypoint:
    - /bin/sh
    - -c
    - "wait-for-it.sh -t 30 rabbit:5672 -- fuzzm --target rabbit /root/model/input.lus"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
    - "15672"
    - "5672"
  printreceiver:
    build: 
      context: .
      args:
      - proxy=${HTTP_PROXY}
    image: printreceiver:latest
    links:
    - rabbit
    volumes:
    - .:/root/print
    entrypoint:
    - /bin/sh
    - -c
    - "wait-for-it.sh -t 30 rabbit:5672 -- python3 print_receiver.py -H rabbit"
